package country

import (
	"fmt"
	"strings"
)

// Code is an ISO 3166-1 alpha-2 code.
type Code string

// Parse converts a string value to a country, and is the only way a Code
// should be obtained from user input. An empty value parses to the empty
// Code, which means "anywhere" rather than "invalid".
func Parse(value string) (Code, error) {
	code := strings.ToUpper(strings.TrimSpace(value))
	if code == "" {
		return "", nil
	}
	if len(code) != 2 {
		return "", fmt.Errorf("country: invalid - %q, use a two letter ISO code such as KE", value)
	}
	return Code(code), nil
}

// String implements fmt.Stringer on Code.
func (c Code) String() string {
	return string(c)
}

// Code constants.
const (
	Andorra                                       Code = "AD"
	UnitedArabEmirates                            Code = "AE"
	Afghanistan                                   Code = "AF"
	AntiguaAndBarbuda                             Code = "AG"
	Anguilla                                      Code = "AI"
	Albania                                       Code = "AL"
	Armenia                                       Code = "AM"
	Angola                                        Code = "AO"
	Antarctica                                    Code = "AQ"
	Argentina                                     Code = "AR"
	AmericanSamoa                                 Code = "AS"
	Austria                                       Code = "AT"
	Australia                                     Code = "AU"
	Aruba                                         Code = "AW"
	AlandIslands                                  Code = "AX" // Åland Islands
	Azerbaijan                                    Code = "AZ"
	BosniaAndHerzegovina                          Code = "BA"
	Barbados                                      Code = "BB"
	Bangladesh                                    Code = "BD"
	Belgium                                       Code = "BE"
	BurkinaFaso                                   Code = "BF"
	Bulgaria                                      Code = "BG"
	Bahrain                                       Code = "BH"
	Burundi                                       Code = "BI"
	Benin                                         Code = "BJ"
	SaintBarthelemy                               Code = "BL" // Saint Barthélemy
	Bermuda                                       Code = "BM"
	BruneiDarussalam                              Code = "BN"
	BoliviaPlurinationalStateOf                   Code = "BO"
	BonaireSintEustatiusAndSaba                   Code = "BQ"
	Brazil                                        Code = "BR"
	Bahamas                                       Code = "BS"
	Bhutan                                        Code = "BT"
	BouvetIsland                                  Code = "BV"
	Botswana                                      Code = "BW"
	Belarus                                       Code = "BY"
	Belize                                        Code = "BZ"
	Canada                                        Code = "CA"
	CocosKeelingIslands                           Code = "CC"
	CongoDemocraticRepublicOfThe                  Code = "CD"
	CentralAfricanRepublic                        Code = "CF"
	Congo                                         Code = "CG"
	Switzerland                                   Code = "CH"
	CoteDIvoire                                   Code = "CI" // Côte d'Ivoire
	CookIslands                                   Code = "CK"
	Chile                                         Code = "CL"
	Cameroon                                      Code = "CM"
	China                                         Code = "CN"
	Colombia                                      Code = "CO"
	CostaRica                                     Code = "CR"
	Cuba                                          Code = "CU"
	CaboVerde                                     Code = "CV"
	Curacao                                       Code = "CW" // Curaçao
	ChristmasIsland                               Code = "CX"
	Cyprus                                        Code = "CY"
	Czechia                                       Code = "CZ"
	Germany                                       Code = "DE"
	Djibouti                                      Code = "DJ"
	Denmark                                       Code = "DK"
	Dominica                                      Code = "DM"
	DominicanRepublic                             Code = "DO"
	Algeria                                       Code = "DZ"
	Ecuador                                       Code = "EC"
	Estonia                                       Code = "EE"
	Egypt                                         Code = "EG"
	WesternSahara                                 Code = "EH"
	Eritrea                                       Code = "ER"
	Spain                                         Code = "ES"
	Ethiopia                                      Code = "ET"
	Finland                                       Code = "FI"
	Fiji                                          Code = "FJ"
	FalklandIslandsMalvinas                       Code = "FK"
	MicronesiaFederatedStatesOf                   Code = "FM"
	FaroeIslands                                  Code = "FO"
	France                                        Code = "FR"
	Gabon                                         Code = "GA"
	UnitedKingdomOfGreatBritainAndNorthernIreland Code = "GB"
	Grenada                                       Code = "GD"
	Georgia                                       Code = "GE"
	FrenchGuiana                                  Code = "GF"
	Guernsey                                      Code = "GG"
	Ghana                                         Code = "GH"
	Gibraltar                                     Code = "GI"
	Greenland                                     Code = "GL"
	Gambia                                        Code = "GM"
	Guinea                                        Code = "GN"
	Guadeloupe                                    Code = "GP"
	EquatorialGuinea                              Code = "GQ"
	Greece                                        Code = "GR"
	SouthGeorgiaAndTheSouthSandwichIslands        Code = "GS"
	Guatemala                                     Code = "GT"
	Guam                                          Code = "GU"
	GuineaBissau                                  Code = "GW"
	Guyana                                        Code = "GY"
	HongKong                                      Code = "HK"
	HeardIslandAndMcDonaldIslands                 Code = "HM"
	Honduras                                      Code = "HN"
	Croatia                                       Code = "HR"
	Haiti                                         Code = "HT"
	Hungary                                       Code = "HU"
	Indonesia                                     Code = "ID"
	Ireland                                       Code = "IE"
	Israel                                        Code = "IL"
	IsleOfMan                                     Code = "IM"
	India                                         Code = "IN"
	BritishIndianOceanTerritory                   Code = "IO"
	Iraq                                          Code = "IQ"
	IranIslamicRepublicOf                         Code = "IR"
	Iceland                                       Code = "IS"
	Italy                                         Code = "IT"
	Jersey                                        Code = "JE"
	Jamaica                                       Code = "JM"
	Jordan                                        Code = "JO"
	Japan                                         Code = "JP"
	Kenya                                         Code = "KE"
	Kyrgyzstan                                    Code = "KG"
	Cambodia                                      Code = "KH"
	Kiribati                                      Code = "KI"
	Comoros                                       Code = "KM"
	SaintKittsAndNevis                            Code = "KN"
	NorthKorea                                    Code = "KP"
	KoreaRepublicOf                               Code = "KR"
	Kuwait                                        Code = "KW"
	CaymanIslands                                 Code = "KY"
	Kazakhstan                                    Code = "KZ"
	LaoPeoplesDemocraticRepublic                  Code = "LA"
	Lebanon                                       Code = "LB"
	SaintLucia                                    Code = "LC"
	Liechtenstein                                 Code = "LI"
	SriLanka                                      Code = "LK"
	Liberia                                       Code = "LR"
	Lesotho                                       Code = "LS"
	Lithuania                                     Code = "LT"
	Luxembourg                                    Code = "LU"
	Latvia                                        Code = "LV"
	Libya                                         Code = "LY"
	Morocco                                       Code = "MA"
	Monaco                                        Code = "MC"
	MoldovaRepublicOf                             Code = "MD"
	Montenegro                                    Code = "ME"
	SaintMartinFrenchPart                         Code = "MF"
	Madagascar                                    Code = "MG"
	MarshallIslands                               Code = "MH"
	NorthMacedonia                                Code = "MK"
	Mali                                          Code = "ML"
	Myanmar                                       Code = "MM"
	Mongolia                                      Code = "MN"
	Macao                                         Code = "MO"
	NorthernMarianaIslands                        Code = "MP"
	Martinique                                    Code = "MQ"
	Mauritania                                    Code = "MR"
	Montserrat                                    Code = "MS"
	Malta                                         Code = "MT"
	Mauritius                                     Code = "MU"
	Maldives                                      Code = "MV"
	Malawi                                        Code = "MW"
	Mexico                                        Code = "MX"
	Malaysia                                      Code = "MY"
	Mozambique                                    Code = "MZ"
	Namibia                                       Code = "NA"
	NewCaledonia                                  Code = "NC"
	Niger                                         Code = "NE"
	NorfolkIsland                                 Code = "NF"
	Nigeria                                       Code = "NG"
	Nicaragua                                     Code = "NI"
	NetherlandsKingdomOfThe                       Code = "NL"
	Norway                                        Code = "NO"
	Nepal                                         Code = "NP"
	Naoero                                        Code = "NR"
	Niue                                          Code = "NU"
	NewZealand                                    Code = "NZ"
	Oman                                          Code = "OM"
	Panama                                        Code = "PA"
	Peru                                          Code = "PE"
	FrenchPolynesia                               Code = "PF"
	PapuaNewGuinea                                Code = "PG"
	Philippines                                   Code = "PH"
	Pakistan                                      Code = "PK"
	Poland                                        Code = "PL"
	SaintPierreAndMiquelon                        Code = "PM"
	Pitcairn                                      Code = "PN"
	PuertoRico                                    Code = "PR"
	PalestineStateOf                              Code = "PS"
	Portugal                                      Code = "PT"
	Palau                                         Code = "PW"
	Paraguay                                      Code = "PY"
	Qatar                                         Code = "QA"
	Reunion                                       Code = "RE" // Réunion
	Romania                                       Code = "RO"
	Serbia                                        Code = "RS"
	RussianFederation                             Code = "RU"
	Rwanda                                        Code = "RW"
	SaudiArabia                                   Code = "SA"
	SolomonIslands                                Code = "SB"
	Seychelles                                    Code = "SC"
	Sudan                                         Code = "SD"
	Sweden                                        Code = "SE"
	Singapore                                     Code = "SG"
	SaintHelenaAscensionAndTristanDaCunha         Code = "SH"
	Slovenia                                      Code = "SI"
	SvalbardAndJanMayen                           Code = "SJ"
	Slovakia                                      Code = "SK"
	SierraLeone                                   Code = "SL"
	SanMarino                                     Code = "SM"
	Senegal                                       Code = "SN"
	Somalia                                       Code = "SO"
	Suriname                                      Code = "SR"
	SouthSudan                                    Code = "SS"
	SaoTomeAndPrincipe                            Code = "ST"
	ElSalvador                                    Code = "SV"
	SintMaartenDutchPart                          Code = "SX"
	SyrianArabRepublic                            Code = "SY"
	Eswatini                                      Code = "SZ"
	TurksAndCaicosIslands                         Code = "TC"
	Chad                                          Code = "TD"
	FrenchSouthernTerritories                     Code = "TF"
	Togo                                          Code = "TG"
	Thailand                                      Code = "TH"
	Tajikistan                                    Code = "TJ"
	Tokelau                                       Code = "TK"
	TimorLeste                                    Code = "TL"
	Turkmenistan                                  Code = "TM"
	Tunisia                                       Code = "TN"
	Tonga                                         Code = "TO"
	Turkiye                                       Code = "TR" // Türkiye
	TrinidadAndTobago                             Code = "TT"
	Tuvalu                                        Code = "TV"
	TaiwanProvinceOfChina                         Code = "TW"
	TanzaniaUnitedRepublicOf                      Code = "TZ"
	Ukraine                                       Code = "UA"
	Uganda                                        Code = "UG"
	UnitedStatesMinorOutlyingIslands              Code = "UM"
	UnitedStatesOfAmerica                         Code = "US"
	Uruguay                                       Code = "UY"
	Uzbekistan                                    Code = "UZ"
	HolySee                                       Code = "VA"
	SaintVincentAndTheGrenadines                  Code = "VC"
	VenezuelaBolivarianRepublicOf                 Code = "VE"
	VirginIslandsBritish                          Code = "VG"
	VirginIslandsUS                               Code = "VI"
	VietNam                                       Code = "VN"
	Vanuatu                                       Code = "VU"
	WallisAndFutuna                               Code = "WF"
	Samoa                                         Code = "WS"
	Yemen                                         Code = "YE"
	Mayotte                                       Code = "YT"
	SouthAfrica                                   Code = "ZA"
	Zambia                                        Code = "ZM"
	Zimbabwe                                      Code = "ZW"
)
