// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sightings.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const sightingCreate = `-- name: SightingCreate :one
INSERT INTO sightings (
	id,
	gbif_key,
	occurrence_id,
	happened_at,
	basis_of_record,
	recorded_by,
	individual_count,
	remarks,
	reference_url,
	locality,
	state_province,
	country,
	country_code,
	latitude,
	longitude,
	coordinate_uncertainty_in_metres,
	elevation_in_metres,
	species_id,
	weather_id,
	media
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, created_at, updated_at, gbif_key, occurrence_id, happened_at, basis_of_record, recorded_by, individual_count, remarks, reference_url, locality, state_province, country, country_code, latitude, longitude, coordinate_uncertainty_in_metres, elevation_in_metres, species_id, weather_id, media
`

type SightingCreateParams struct {
	ID                            uuid.UUID `db:"id" json:"id"`
	GbifKey                       int64     `db:"gbif_key" json:"gbif_key"`
	OccurrenceID                  string    `db:"occurrence_id" json:"occurrence_id"`
	HappenedAt                    time.Time `db:"happened_at" json:"happened_at"`
	BasisOfRecord                 string    `db:"basis_of_record" json:"basis_of_record"`
	RecordedBy                    string    `db:"recorded_by" json:"recorded_by"`
	IndividualCount               *int      `db:"individual_count" json:"individual_count"`
	Remarks                       string    `db:"remarks" json:"remarks"`
	ReferenceUrl                  string    `db:"reference_url" json:"reference_url"`
	Locality                      string    `db:"locality" json:"locality"`
	StateProvince                 string    `db:"state_province" json:"state_province"`
	Country                       string    `db:"country" json:"country"`
	CountryCode                   string    `db:"country_code" json:"country_code"`
	Latitude                      float64   `db:"latitude" json:"latitude"`
	Longitude                     float64   `db:"longitude" json:"longitude"`
	CoordinateUncertaintyInMetres *float64  `db:"coordinate_uncertainty_in_metres" json:"coordinate_uncertainty_in_metres"`
	ElevationInMetres             *float64  `db:"elevation_in_metres" json:"elevation_in_metres"`
	SpeciesID                     uuid.UUID `db:"species_id" json:"species_id"`
	WeatherID                     uuid.UUID `db:"weather_id" json:"weather_id"`
	Media                         string    `db:"media" json:"media"`
}

func (q *Queries) SightingCreate(ctx context.Context, arg SightingCreateParams) (Sighting, error) {
	row := q.db.QueryRowContext(ctx, sightingCreate,
		arg.ID,
		arg.GbifKey,
		arg.OccurrenceID,
		arg.HappenedAt,
		arg.BasisOfRecord,
		arg.RecordedBy,
		arg.IndividualCount,
		arg.Remarks,
		arg.ReferenceUrl,
		arg.Locality,
		arg.StateProvince,
		arg.Country,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.CoordinateUncertaintyInMetres,
		arg.ElevationInMetres,
		arg.SpeciesID,
		arg.WeatherID,
		arg.Media,
	)
	var i Sighting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GbifKey,
		&i.OccurrenceID,
		&i.HappenedAt,
		&i.BasisOfRecord,
		&i.RecordedBy,
		&i.IndividualCount,
		&i.Remarks,
		&i.ReferenceUrl,
		&i.Locality,
		&i.StateProvince,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.CoordinateUncertaintyInMetres,
		&i.ElevationInMetres,
		&i.SpeciesID,
		&i.WeatherID,
		&i.Media,
	)
	return i, err
}

const sightingFind = `-- name: SightingFind :one
SELECT sightings.id, sightings.created_at, sightings.updated_at, sightings.gbif_key, sightings.occurrence_id, sightings.happened_at, sightings.basis_of_record, sightings.recorded_by, sightings.individual_count, sightings.remarks, sightings.reference_url, sightings.locality, sightings.state_province, sightings.country, sightings.country_code, sightings.latitude, sightings.longitude, sightings.coordinate_uncertainty_in_metres, sightings.elevation_in_metres, sightings.species_id, sightings.weather_id, sightings.media, species.id, species.created_at, species.updated_at, species.gbif_key, species.kingdom, species.phylum, species.class, species."order", species.family, species.genus, species.species, species.rank, species.scientific_name, species.canonical_name, species.vernacular_name
FROM sightings
	JOIN species ON species.id = sightings.species_id
WHERE sightings.id = ?
`

type SightingFindRow struct {
	Sighting Sighting `db:"sighting" json:"sighting"`
	Species  Species  `db:"species" json:"species"`
}

func (q *Queries) SightingFind(ctx context.Context, id uuid.UUID) (SightingFindRow, error) {
	row := q.db.QueryRowContext(ctx, sightingFind, id)
	var i SightingFindRow
	err := row.Scan(
		&i.Sighting.ID,
		&i.Sighting.CreatedAt,
		&i.Sighting.UpdatedAt,
		&i.Sighting.GbifKey,
		&i.Sighting.OccurrenceID,
		&i.Sighting.HappenedAt,
		&i.Sighting.BasisOfRecord,
		&i.Sighting.RecordedBy,
		&i.Sighting.IndividualCount,
		&i.Sighting.Remarks,
		&i.Sighting.ReferenceUrl,
		&i.Sighting.Locality,
		&i.Sighting.StateProvince,
		&i.Sighting.Country,
		&i.Sighting.CountryCode,
		&i.Sighting.Latitude,
		&i.Sighting.Longitude,
		&i.Sighting.CoordinateUncertaintyInMetres,
		&i.Sighting.ElevationInMetres,
		&i.Sighting.SpeciesID,
		&i.Sighting.WeatherID,
		&i.Sighting.Media,
		&i.Species.ID,
		&i.Species.CreatedAt,
		&i.Species.UpdatedAt,
		&i.Species.GbifKey,
		&i.Species.Kingdom,
		&i.Species.Phylum,
		&i.Species.Class,
		&i.Species.Order,
		&i.Species.Family,
		&i.Species.Genus,
		&i.Species.Species,
		&i.Species.Rank,
		&i.Species.ScientificName,
		&i.Species.CanonicalName,
		&i.Species.VernacularName,
	)
	return i, err
}

const sightingFindByGbifKey = `-- name: SightingFindByGbifKey :one
SELECT sightings.id, sightings.created_at, sightings.updated_at, sightings.gbif_key, sightings.occurrence_id, sightings.happened_at, sightings.basis_of_record, sightings.recorded_by, sightings.individual_count, sightings.remarks, sightings.reference_url, sightings.locality, sightings.state_province, sightings.country, sightings.country_code, sightings.latitude, sightings.longitude, sightings.coordinate_uncertainty_in_metres, sightings.elevation_in_metres, sightings.species_id, sightings.weather_id, sightings.media, species.id, species.created_at, species.updated_at, species.gbif_key, species.kingdom, species.phylum, species.class, species."order", species.family, species.genus, species.species, species.rank, species.scientific_name, species.canonical_name, species.vernacular_name
FROM sightings
	JOIN species ON species.id = sightings.species_id
WHERE sightings.gbif_key = ?
`

type SightingFindByGbifKeyRow struct {
	Sighting Sighting `db:"sighting" json:"sighting"`
	Species  Species  `db:"species" json:"species"`
}

func (q *Queries) SightingFindByGbifKey(ctx context.Context, gbifKey int64) (SightingFindByGbifKeyRow, error) {
	row := q.db.QueryRowContext(ctx, sightingFindByGbifKey, gbifKey)
	var i SightingFindByGbifKeyRow
	err := row.Scan(
		&i.Sighting.ID,
		&i.Sighting.CreatedAt,
		&i.Sighting.UpdatedAt,
		&i.Sighting.GbifKey,
		&i.Sighting.OccurrenceID,
		&i.Sighting.HappenedAt,
		&i.Sighting.BasisOfRecord,
		&i.Sighting.RecordedBy,
		&i.Sighting.IndividualCount,
		&i.Sighting.Remarks,
		&i.Sighting.ReferenceUrl,
		&i.Sighting.Locality,
		&i.Sighting.StateProvince,
		&i.Sighting.Country,
		&i.Sighting.CountryCode,
		&i.Sighting.Latitude,
		&i.Sighting.Longitude,
		&i.Sighting.CoordinateUncertaintyInMetres,
		&i.Sighting.ElevationInMetres,
		&i.Sighting.SpeciesID,
		&i.Sighting.WeatherID,
		&i.Sighting.Media,
		&i.Species.ID,
		&i.Species.CreatedAt,
		&i.Species.UpdatedAt,
		&i.Species.GbifKey,
		&i.Species.Kingdom,
		&i.Species.Phylum,
		&i.Species.Class,
		&i.Species.Order,
		&i.Species.Family,
		&i.Species.Genus,
		&i.Species.Species,
		&i.Species.Rank,
		&i.Species.ScientificName,
		&i.Species.CanonicalName,
		&i.Species.VernacularName,
	)
	return i, err
}

const sightingList = `-- name: SightingList :many
SELECT sightings.id, sightings.created_at, sightings.updated_at, sightings.gbif_key, sightings.occurrence_id, sightings.happened_at, sightings.basis_of_record, sightings.recorded_by, sightings.individual_count, sightings.remarks, sightings.reference_url, sightings.locality, sightings.state_province, sightings.country, sightings.country_code, sightings.latitude, sightings.longitude, sightings.coordinate_uncertainty_in_metres, sightings.elevation_in_metres, sightings.species_id, sightings.weather_id, sightings.media, species.id, species.created_at, species.updated_at, species.gbif_key, species.kingdom, species.phylum, species.class, species."order", species.family, species.genus, species.species, species.rank, species.scientific_name, species.canonical_name, species.vernacular_name
FROM sightings
	JOIN species ON species.id = sightings.species_id
WHERE (?1 IS NULL OR happened_at >= ?1)
	AND (?2 IS NULL OR happened_at <= ?2)
	AND (?3 = '' OR sightings.country_code = ?3)
	AND (CAST(?4 AS BOOLEAN) OR species.gbif_key IN (SELECT value FROM json_each(?5)))
ORDER BY sightings.happened_at DESC, sightings.id DESC
LIMIT ?6
`

type SightingListParams struct {
	FromDate    interface{} `db:"from_date" json:"from_date"`
	ToDate      interface{} `db:"to_date" json:"to_date"`
	CountryCode interface{} `db:"country_code" json:"country_code"`
	AnySpecies  bool        `db:"any_species" json:"any_species"`
	SpeciesKeys interface{} `db:"species_keys" json:"species_keys"`
	Limit       int64       `db:"limit" json:"limit"`
}

type SightingListRow struct {
	Sighting Sighting `db:"sighting" json:"sighting"`
	Species  Species  `db:"species" json:"species"`
}

func (q *Queries) SightingList(ctx context.Context, arg SightingListParams) ([]SightingListRow, error) {
	rows, err := q.db.QueryContext(ctx, sightingList,
		arg.FromDate,
		arg.ToDate,
		arg.CountryCode,
		arg.AnySpecies,
		arg.SpeciesKeys,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SightingListRow{}
	for rows.Next() {
		var i SightingListRow
		if err := rows.Scan(
			&i.Sighting.ID,
			&i.Sighting.CreatedAt,
			&i.Sighting.UpdatedAt,
			&i.Sighting.GbifKey,
			&i.Sighting.OccurrenceID,
			&i.Sighting.HappenedAt,
			&i.Sighting.BasisOfRecord,
			&i.Sighting.RecordedBy,
			&i.Sighting.IndividualCount,
			&i.Sighting.Remarks,
			&i.Sighting.ReferenceUrl,
			&i.Sighting.Locality,
			&i.Sighting.StateProvince,
			&i.Sighting.Country,
			&i.Sighting.CountryCode,
			&i.Sighting.Latitude,
			&i.Sighting.Longitude,
			&i.Sighting.CoordinateUncertaintyInMetres,
			&i.Sighting.ElevationInMetres,
			&i.Sighting.SpeciesID,
			&i.Sighting.WeatherID,
			&i.Sighting.Media,
			&i.Species.ID,
			&i.Species.CreatedAt,
			&i.Species.UpdatedAt,
			&i.Species.GbifKey,
			&i.Species.Kingdom,
			&i.Species.Phylum,
			&i.Species.Class,
			&i.Species.Order,
			&i.Species.Family,
			&i.Species.Genus,
			&i.Species.Species,
			&i.Species.Rank,
			&i.Species.ScientificName,
			&i.Species.CanonicalName,
			&i.Species.VernacularName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
