// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package db

import (
	"context"

	"uuid"
)

const speciesCreate = `-- name: SpeciesCreate :one
INSERT INTO species (id, "gbif_key", "kingdom", "phylum", "class", "order", "family", "genus", "species", "rank", "scientific_name", "canonical_name", "vernacular_name")
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, created_at, updated_at, gbif_key, kingdom, phylum, class, "order", family, genus, species, rank, scientific_name, canonical_name, vernacular_name
`

type SpeciesCreateParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	GbifKey        int64     `db:"gbif_key" json:"gbif_key"`
	Kingdom        string    `db:"kingdom" json:"kingdom"`
	Phylum         string    `db:"phylum" json:"phylum"`
	Class          string    `db:"class" json:"class"`
	Order          string    `db:"order" json:"order"`
	Family         string    `db:"family" json:"family"`
	Genus          string    `db:"genus" json:"genus"`
	Species        string    `db:"species" json:"species"`
	Rank           string    `db:"rank" json:"rank"`
	ScientificName string    `db:"scientific_name" json:"scientific_name"`
	CanonicalName  string    `db:"canonical_name" json:"canonical_name"`
	VernacularName string    `db:"vernacular_name" json:"vernacular_name"`
}

func (q *Queries) SpeciesCreate(ctx context.Context, arg SpeciesCreateParams) (Species, error) {
	row := q.db.QueryRowContext(ctx, speciesCreate,
		arg.ID,
		arg.GbifKey,
		arg.Kingdom,
		arg.Phylum,
		arg.Class,
		arg.Order,
		arg.Family,
		arg.Genus,
		arg.Species,
		arg.Rank,
		arg.ScientificName,
		arg.CanonicalName,
		arg.VernacularName,
	)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GbifKey,
		&i.Kingdom,
		&i.Phylum,
		&i.Class,
		&i.Order,
		&i.Family,
		&i.Genus,
		&i.Species,
		&i.Rank,
		&i.ScientificName,
		&i.CanonicalName,
		&i.VernacularName,
	)
	return i, err
}

const speciesFind = `-- name: SpeciesFind :one
SELECT id, created_at, updated_at, gbif_key, kingdom, phylum, class, "order", family, genus, species, rank, scientific_name, canonical_name, vernacular_name FROM species WHERE id = ?
`

func (q *Queries) SpeciesFind(ctx context.Context, id uuid.UUID) (Species, error) {
	row := q.db.QueryRowContext(ctx, speciesFind, id)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GbifKey,
		&i.Kingdom,
		&i.Phylum,
		&i.Class,
		&i.Order,
		&i.Family,
		&i.Genus,
		&i.Species,
		&i.Rank,
		&i.ScientificName,
		&i.CanonicalName,
		&i.VernacularName,
	)
	return i, err
}

const speciesFindByGbifKey = `-- name: SpeciesFindByGbifKey :one
SELECT id, created_at, updated_at, gbif_key, kingdom, phylum, class, "order", family, genus, species, rank, scientific_name, canonical_name, vernacular_name FROM species WHERE gbif_key = ?
`

func (q *Queries) SpeciesFindByGbifKey(ctx context.Context, gbifKey int64) (Species, error) {
	row := q.db.QueryRowContext(ctx, speciesFindByGbifKey, gbifKey)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GbifKey,
		&i.Kingdom,
		&i.Phylum,
		&i.Class,
		&i.Order,
		&i.Family,
		&i.Genus,
		&i.Species,
		&i.Rank,
		&i.ScientificName,
		&i.CanonicalName,
		&i.VernacularName,
	)
	return i, err
}

const speciesList = `-- name: SpeciesList :many
SELECT id, created_at, updated_at, gbif_key, kingdom, phylum, class, "order", family, genus, species, rank, scientific_name, canonical_name, vernacular_name FROM species
`

func (q *Queries) SpeciesList(ctx context.Context) ([]Species, error) {
	rows, err := q.db.QueryContext(ctx, speciesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Species{}
	for rows.Next() {
		var i Species
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GbifKey,
			&i.Kingdom,
			&i.Phylum,
			&i.Class,
			&i.Order,
			&i.Family,
			&i.Genus,
			&i.Species,
			&i.Rank,
			&i.ScientificName,
			&i.CanonicalName,
			&i.VernacularName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
