// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const weatherCreate = `-- name: WeatherCreate :one
INSERT INTO weather (
	id,
	observed_at,
	temperature,
	apparent_temperature
) VALUES (?, ?, ?, ?) RETURNING id, created_at, updated_at, observed_at, temperature, apparent_temperature
`

type WeatherCreateParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	ObservedAt          time.Time `db:"observed_at" json:"observed_at"`
	Temperature         *int      `db:"temperature" json:"temperature"`
	ApparentTemperature *int      `db:"apparent_temperature" json:"apparent_temperature"`
}

func (q *Queries) WeatherCreate(ctx context.Context, arg WeatherCreateParams) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherCreate,
		arg.ID,
		arg.ObservedAt,
		arg.Temperature,
		arg.ApparentTemperature,
	)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Temperature,
		&i.ApparentTemperature,
	)
	return i, err
}

const weatherFind = `-- name: WeatherFind :one
SELECT id, created_at, updated_at, observed_at, temperature, apparent_temperature FROM weather WHERE id = ?
`

func (q *Queries) WeatherFind(ctx context.Context, id uuid.UUID) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherFind, id)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Temperature,
		&i.ApparentTemperature,
	)
	return i, err
}
